import os
from dotenv import load_dotenv
import environ

env = environ.Env()

env.read_env(".env")

load_dotenv()

class Config(object):
    # PostgreSQL
    POSTGRES_URL = env("POSTGRES_URL")
    POSTGRES_USER = env("POSTGRES_USER")
    POSTGRES_PW = env("POSTGRES_PW") 
    POSTGRES_DB = env("POSTGRES_DB")
    SQLALCHEMY_DATABASE_URI = f'postgresql://{POSTGRES_USER}:{POSTGRES_PW}@{POSTGRES_URL}/{POSTGRES_DB}'
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    # FirebaseAdminConfiguration
    FIREBASE_TYPE = env("FIREBASE_TYPE")
    FIREBASE_PROJECT_ID = env("FIREBASE_PROJECT_ID")
    FIREBASE_PRIVATE_KEY_ID = env("FIREBASE_PRIVATE_KEY_ID")
    FIREBASE_PRIVATE_KEY = env("FIREBASE_PRIVATE_KEY")
    FIREBASE_CLIENT_EMAIL = env("FIREBASE_CLIENT_EMAIL")
    FIREBASE_CLIENT_ID = env("FIREBASE_CLIENT_ID")
    FIREBASE_AUTH_URI = env("FIREBASE_AUTH_URI")
    FIREBASE_TOKEN_URI = env("FIREBASE_TOKEN_URI")
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL = env("FIREBASE_AUTH_PROVIDER_X509_CERT_URL")
    FIREBASE_CLIENT_X509_CERT_URL = env("FIREBASE_CLIENT_X509_CERT_URL")

    #FirebaseUI
    FIREBASE_API_KEY = env("FIREBASE_API_KEY")
    FIREBASE_AUTH_DOMAIN = env("FIREBASE_AUTH_DOMAIN")
    FIREBASE_PROJECT_ID = env("FIREBASE_PROJECT_ID")
    FIREBASE_STORAGE_BUCKET = env("FIREBASE_STORAGE_BUCKET")
    FIREBASE_MESSAGING_SENDER_ID = env("FIREBASE_MESSAGING_SENDER_ID")
    FIREBASE_APP_ID = env("FIREBASE_APP_ID ")

    # OpenAI
    OPENAI_API_KEY = env("OPENAI_API_KEY")

    # NCBI
    NCBI_API_KEY = env("NCBI_API_KEY")
    NCBI_API_EMAIL = env("NCBI_API_EMAIL")

    # Redis
    REDIS_HOST = env("REDIS_HOST")
    REDIS_PORT = env("REDIS_PORT")
    REDIS_DB = env("REDIS_DB")

    # Wolfram
    WOLFRAM_APP_NAME = env("WOLFRAM_APP_NAME")
    WOLFRAM_APP_ID = env("WOLFRAM_APP_ID")
